import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  

		int countFamiliesTwo = 0;
		int countFamiliesThree = 0;
		int countFamiliesMore = 0;
		double countChildrenAll = 0;
		
		for (int i = 0; i < T; i++){
			
			boolean g = false;
			boolean b = false;
			int countChildren = 0;

			//Playing Sims in java 
			do {
				double random = generator.nextDouble();
				if (random < 0.5)g = true;
				else b = true;
				countChildren += 1;
			}
			while ((g && b) == false);

			//Add to stats
			if (countChildren == 2) countFamiliesTwo += 1;
			if (countChildren == 3) countFamiliesThree += 1;
			else countFamiliesMore += 1;
			countChildrenAll += countChildren;
			
		}

		//Calculates the average
		double countChildrenAverage = (countChildrenAll / T);
		
		//Detects which option is mode
		String whoIsMode;
		int mode = Math.max(Math.max(countFamiliesTwo, countFamiliesThree), countFamiliesMore);
		if (mode == countFamiliesTwo) whoIsMode = "The most common number of children is 2.";
		else if (mode == countFamiliesThree) whoIsMode = "The most common number of children is 3.";
		else whoIsMode = "The most common number of children is 4 or more.";
		
		System.out.println("Average: " + countChildrenAverage + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + countFamiliesTwo);
		System.out.println("Number of families with 3 children: " + countFamiliesThree);
		System.out.println("Number of families with 4 or more children: " + countFamiliesMore);
		System.out.println(whoIsMode);

	}
}
